#!/bin/bash

# Install Nginx if not already installed
apt-get update
apt-get install nginx -y

# Configure Nginx to listen on port 80 of all active IPv4 IPs
sed -i '/listen 80;/c\    listen 80 default_server;' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart